/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.

mostrar y ocultar jpassword
https://es.stackoverflow.com/questions/90900/c%C3%B3mo-mostrar-y-ocultar-una-contrase%C3%B1a-en-un-jpasswordfield


 */
package Index;

import Conexion.Conexion;
import Mail.Mail;
import Recursos.Configuracion;
import Recursos.Utiles;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabian
 */
public class Servidor extends javax.swing.JFrame {

    String fechaActual;
    String horaActual;
    boolean mailAut;
    boolean dataAut;
    Conexion conexion;
    Mail mail;

    public Servidor(String correo, String contrasenia, String nombreEmpresa, String servidorSmtp, String puerto) {
        initComponents();
        this.setTitle("Configuración del Sistema");
        conexion = new Conexion();
        mail = new Mail();
        this.txtNombreEmpresa.requestFocus();
        if (nombreEmpresa != null) {
            this.txtNombreEmpresa.setText(nombreEmpresa);
            this.txtServidorSmtp.setText(servidorSmtp);
            this.txtPuerto.setText(puerto);
            this.txtCorreo.setText(correo);
            this.jpassword.setText(contrasenia);
        } else {
            this.txtNombreEmpresa.setText("NOMBRE EMPRESA S.A.S.");
            this.txtServidorSmtp.setText("mail.servidorSmtp.com");
            this.txtPuerto.setText("587");
            this.txtCorreo.setText("correo@tuempresa.com");
            this.jpassword.setText("ContraseniaDeTuCorreoElectronico");
        }
        mailAut = false;

        //Validar cada campo de texto
        txtPuerto.addKeyListener(new KeyListener() {

            public void keyTyped(KeyEvent e) {
                //Validar si es solo numérico
                char caracter = e.getKeyChar();
                // Verificar si la tecla pulsada no es un digito
                if (((caracter < '0')
                        || (caracter > '9'))
                        && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
                    e.consume();  // ignorar el evento de teclado
                }
                //Validar para que solo pueda escribir un numero determinado de caracteres
                if (txtPuerto.getText().length() == Configuracion.numeroDeCaractaresNumericosEnElPuerto) {
                    e.consume();
                }
            }

            public void keyPressed(KeyEvent arg0) {
            }

            public void keyReleased(KeyEvent arg0) {
            }
        });
    }

    private void cargarCursor(boolean cargar) {
        if (cargar) {
            //cursor para buscar
            getContentPane().setCursor(new Cursor(Cursor.WAIT_CURSOR));
        } else {
            //Dejamos el cursor por defecto
            getContentPane().setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelServidor = new javax.swing.JPanel();
        panelFooter = new javax.swing.JPanel();
        btnIniciarSesion = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        panelConfigMail = new javax.swing.JPanel();
        txtNombreEmpresa = new javax.swing.JTextField();
        txtServidorSmtp = new javax.swing.JTextField();
        txtPuerto = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jpassword = new javax.swing.JPasswordField();
        lblNombreEmpresa = new javax.swing.JLabel();
        lblServidorSmtp = new javax.swing.JLabel();
        lblPuerto = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblContrasenia = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        btnIniciarSesion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        btnIniciarSesion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnIniciarSesionKeyTyped(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        btnSalir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnSalirKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelFooterLayout = new javax.swing.GroupLayout(panelFooter);
        panelFooter.setLayout(panelFooterLayout);
        panelFooterLayout.setHorizontalGroup(
            panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFooterLayout.createSequentialGroup()
                .addContainerGap(428, Short.MAX_VALUE)
                .addComponent(btnIniciarSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelFooterLayout.setVerticalGroup(
            panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFooterLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        txtNombreEmpresa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNombreEmpresa.setMinimumSize(new java.awt.Dimension(15, 25));
        txtNombreEmpresa.setPreferredSize(new java.awt.Dimension(18, 25));
        txtNombreEmpresa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreEmpresaFocusGained(evt);
            }
        });
        txtNombreEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreEmpresaKeyTyped(evt);
            }
        });

        txtServidorSmtp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtServidorSmtp.setMinimumSize(new java.awt.Dimension(15, 25));
        txtServidorSmtp.setPreferredSize(new java.awt.Dimension(18, 25));
        txtServidorSmtp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtServidorSmtpFocusGained(evt);
            }
        });
        txtServidorSmtp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtServidorSmtpKeyTyped(evt);
            }
        });

        txtPuerto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPuerto.setPreferredSize(new java.awt.Dimension(18, 25));
        txtPuerto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPuertoFocusGained(evt);
            }
        });
        txtPuerto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPuertoKeyTyped(evt);
            }
        });

        txtCorreo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCorreo.setPreferredSize(new java.awt.Dimension(18, 25));
        txtCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCorreoFocusGained(evt);
            }
        });
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCorreoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoKeyTyped(evt);
            }
        });

        jpassword.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jpassword.setPreferredSize(new java.awt.Dimension(18, 23));
        jpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jpasswordFocusGained(evt);
            }
        });
        jpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jpasswordKeyTyped(evt);
            }
        });

        lblNombreEmpresa.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N

        lblServidorSmtp.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N

        lblPuerto.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N

        lblCorreo.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N

        lblContrasenia.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Contraseña de Correo");
        jLabel4.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Puerto SMTP");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Correo");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Nombre Empresa");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Nombre del Servidor SMTP");

        javax.swing.GroupLayout panelConfigMailLayout = new javax.swing.GroupLayout(panelConfigMail);
        panelConfigMail.setLayout(panelConfigMailLayout);
        panelConfigMailLayout.setHorizontalGroup(
            panelConfigMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfigMailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConfigMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelConfigMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPuerto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtServidorSmtp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNombreEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(jpassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelConfigMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(lblPuerto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblServidorSmtp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNombreEmpresa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblContrasenia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelConfigMailLayout.setVerticalGroup(
            panelConfigMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfigMailLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelConfigMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConfigMailLayout.createSequentialGroup()
                        .addGroup(panelConfigMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelConfigMailLayout.createSequentialGroup()
                                .addComponent(txtNombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelConfigMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtServidorSmtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addGroup(panelConfigMailLayout.createSequentialGroup()
                                .addComponent(lblNombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(lblServidorSmtp, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelConfigMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelConfigMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelConfigMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelConfigMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))))
                    .addGroup(panelConfigMailLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelConfigMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)))
        );

        javax.swing.GroupLayout panelServidorLayout = new javax.swing.GroupLayout(panelServidor);
        panelServidor.setLayout(panelServidorLayout);
        panelServidorLayout.setHorizontalGroup(
            panelServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelServidorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelConfigMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelServidorLayout.setVerticalGroup(
            panelServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelServidorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelConfigMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtServidorSmtpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtServidorSmtpKeyTyped
        //capturamos la tecla presionada
        char tecla = evt.getKeyChar();
        if (tecla == KeyEvent.VK_ENTER) {
            if (txtServidorSmtp.getText().equals("")) {
                txtServidorSmtp.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                lblServidorSmtp.setText("Este campo es obligatorio");
            } else {
//                txtServidorSmtp.setBorder(BorderFactory.createCompoundBorder(
//                        txtServidorSmtp.getBorder(),
//                        BorderFactory.createEmptyBorder(5, 5, 5, 5)));
                txtServidorSmtp.setBorder(BorderFactory.createLineBorder(Color.GRAY, 1));
                lblServidorSmtp.setText("");
                txtPuerto.requestFocus();
            }
        }
    }//GEN-LAST:event_txtServidorSmtpKeyTyped

    private void txtPuertoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPuertoKeyTyped

        //capturamos la tecla presionada
        char tecla = evt.getKeyChar();
        if (tecla == KeyEvent.VK_ENTER) {
            if (txtPuerto.getText().equals("")) {
                txtPuerto.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                lblPuerto.setText("Este campo es obligatorio");
            } else {
                txtPuerto.setBorder(BorderFactory.createLineBorder(Color.GRAY, 1));
                lblPuerto.setText("");
                txtCorreo.requestFocus();
            }
        }
    }//GEN-LAST:event_txtPuertoKeyTyped

    private void txtCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyTyped
        //es un correo=?
        boolean si = Utiles.validateEmail(txtCorreo.getText());

        txtCorreo.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = txtCorreo.getText();
                repaint();
                if (!si) {
                    txtCorreo.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                    lblCorreo.setText("Correo no válido (usuario@tuempresa.com)");
                } else {
                    txtCorreo.setBorder(BorderFactory.createLineBorder(Color.GRAY, 1));
                    lblCorreo.setText("");
                }
            }
        });
    }//GEN-LAST:event_txtCorreoKeyTyped


    private void txtNombreEmpresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreEmpresaKeyTyped
        //capturamos la tecla presionada
        char tecla = evt.getKeyChar();
        if (tecla == KeyEvent.VK_ENTER) {
            if (txtNombreEmpresa.getText().equals("")) {
                txtNombreEmpresa.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                lblNombreEmpresa.setText("Este campo es obligatorio");
            } else {
                txtNombreEmpresa.setBorder(BorderFactory.createLineBorder(Color.GRAY, 1));
                lblNombreEmpresa.setText("");
                txtServidorSmtp.requestFocus();
            }
        }
    }//GEN-LAST:event_txtNombreEmpresaKeyTyped

    private void jpasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpasswordKeyTyped
        char tecla = evt.getKeyChar();
        if (tecla == KeyEvent.VK_ENTER) {
            if (jpassword.getText().equals("")) {
                jpassword.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                lblContrasenia.setText("Este campo es obligatorio");
            } else {
                jpassword.setBorder(BorderFactory.createLineBorder(Color.GRAY, 1));
                lblContrasenia.setText("");
                btnIniciarSesion.requestFocus();
            }
        }
    }//GEN-LAST:event_jpasswordKeyTyped

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(rootPane, "Desea Salir del Programa", "¿Está seguro...?", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (res == JOptionPane.YES_OPTION) {
            System.exit(0);
            cargarCursor(true);
            //propiedad que elimina la ventana
            this.dispose();
            this.setVisible(false);
            cargarCursor(false);
        } else if (res == JOptionPane.NO_OPTION) {
            System.out.println("Continuamos...");
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSalirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSalirKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirKeyTyped

    private void btnIniciarSesionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnIniciarSesionKeyTyped
        char tecla = evt.getKeyChar();
        if (tecla == KeyEvent.VK_ENTER) {
            btnIniciarSesion.doClick();
        }
    }//GEN-LAST:event_btnIniciarSesionKeyTyped

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        try {
            if (txtNombreEmpresa.getText().equals("")) {
                txtNombreEmpresa.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                lblNombreEmpresa.setText("Este campo es obligatorio");
                txtNombreEmpresa.requestFocus();
            } else if (txtServidorSmtp.getText().equals("")) {
                txtServidorSmtp.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                lblServidorSmtp.setText("Este campo es obligatorio");
                txtServidorSmtp.requestFocus();
            } else if (txtPuerto.getText().equals("")) {
                txtPuerto.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                lblPuerto.setText("Este campo es obligatorio");
                txtPuerto.requestFocus();
            } else if (txtCorreo.getText().equals("")) {
                txtCorreo.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                lblCorreo.setText("Este campo es obligatorio");
                txtCorreo.requestFocus();
            } else if (jpassword.getText().equals("")) {
                jpassword.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                lblContrasenia.setText("Este campo es obligatorio");
                jpassword.requestFocus();
            } else {
                cargarCursor(true);
                Mail.nombreEmpresa = txtNombreEmpresa.getText();
                Mail.servidorSMTP = txtServidorSmtp.getText();
                Mail.puerto = txtPuerto.getText();
                Mail.userMail = txtCorreo.getText();
                Mail.pass = jpassword.getText();

                //Validamos la configuracion de correo
                if (mail.send(txtCorreo.getText(), Configuracion.asuntoDeIngreso, Configuracion.mensajeDeIngreso)) {
                    //si se envia el correo es porque todos los parametros solicitados estan bien, exportamos los parametros a txt
                    Mail.exportarTxtParametrosDeCorreo(txtNombreEmpresa.getText(), txtServidorSmtp.getText(), txtPuerto.getText(), txtCorreo.getText(), jpassword.getText());
                    mailAut = true;
                    this.dispose();
                    this.setVisible(false);
                    EnviarMail enviarMail = new EnviarMail(true);
                    enviarMail.setVisible(true);
                    cargarCursor(false);
                } else {
                    txtServidorSmtp.requestFocus();
                    cargarCursor(false);
                    JOptionPane.showMessageDialog(null, "Hay un error en la configuración del correo\nRevise la configuración");
                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void txtNombreEmpresaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreEmpresaFocusGained
        // TODO add your handling code here:
        txtNombreEmpresa.selectAll();
    }//GEN-LAST:event_txtNombreEmpresaFocusGained

    private void txtServidorSmtpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtServidorSmtpFocusGained
        // TODO add your handling code here:
        txtServidorSmtp.selectAll();
    }//GEN-LAST:event_txtServidorSmtpFocusGained

    private void txtPuertoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPuertoFocusGained
        // TODO add your handling code here:
        txtPuerto.selectAll();
    }//GEN-LAST:event_txtPuertoFocusGained

    private void txtCorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusGained
        // TODO add your handling code here:
        txtCorreo.selectAll();
    }//GEN-LAST:event_txtCorreoFocusGained

    private void jpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpasswordFocusGained
        // TODO add your handling code here:
        jpassword.selectAll();
    }//GEN-LAST:event_jpasswordFocusGained

    private void txtCorreoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyPressed
        // TODO add your handling code here:

        //es un correo=?
        boolean si = Utiles.validateEmail(txtCorreo.getText());

        //capturamos la tecla presionada
        char tecla = evt.getKeyChar();
        if (tecla == KeyEvent.VK_ENTER) {
            if (txtCorreo.getText().equals("")) {
                txtCorreo.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                lblCorreo.setText("Este campo es obligatorio");
            } else if (!si) {
                txtCorreo.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                lblCorreo.setText("Correo no válido (usuario@tuempresa.com)");
            } else {
                txtCorreo.setBorder(BorderFactory.createLineBorder(Color.GRAY, 1));
                lblCorreo.setText("");
                jpassword.requestFocus();
            }
        }
    }//GEN-LAST:event_txtCorreoKeyPressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblNombreEmpresa;
    private javax.swing.JLabel lblPuerto;
    private javax.swing.JLabel lblServidorSmtp;
    private javax.swing.JPanel panelConfigMail;
    private javax.swing.JPanel panelFooter;
    private javax.swing.JPanel panelServidor;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombreEmpresa;
    private javax.swing.JTextField txtPuerto;
    private javax.swing.JTextField txtServidorSmtp;
    // End of variables declaration//GEN-END:variables
}
